server:
  port: 80

spring:
  data:
    mongodb:
      host: ${SIMPLE_MUSIC_MUSICIANS_STORAGE_HOST}
      port: ${SIMPLE_MUSIC_MUSICIANS_STORAGE_PORT}
      uri: mongodb://${spring.data.mongodb.host}:${spring.data.mongodb.port}/musicians
  cloud:
    consul:
      enabled: true
      host: ${SIMPLE_MUSIC_REGISTRY_HOST}
      port: ${SIMPLE_MUSIC_REGISTRY_PORT}
      discovery:
        instanceId: ${spring.application.name}:${random.value}

security:
  service-id: musicians
  service-password: secret
  token-lifetime: 30
